# Generated by Django 2.1.7 on 2019-10-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Papers',
            new_name='Paper',
        ),
    ]
