export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";

export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const REGISTRATION_SUCCESSFUL = "REGISTRATION_SUCCESSFUL";

export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";

export const GET_PAPERS = "GET_PAPERS";
