export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";

export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const REGISTRATION_SUCCESSFUL = "REGISTRATION_SUCCESSFUL";

export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";

export const GET_PAPERS = "GET_PAPERS";
export const GET_AUTHORS = "GET_AUTHORS";
export const GET_TOPICS = "GET_TOPICS";

export const ADD_AUTHOR_TO_LIKE = "ADD_AUTHOR_TO_LIKE";
export const ADD_PAPER_TO_LIKE = "ADD_PAPER_TO_LIKE";
export const ADD_TOPIC_TO_LIKE = "ADD_TOPIC_TO_LIKE";
export const UPDATE_BASKET = "UPDATE_BASKET";

export const SELECT_AUTHOR = "SELECT_AUTHOR";
export const SELECT_PAPER = "SELECT_PAPER";
export const SELECT_TOPIC = "SELECT_TOPIC";
