# Generated by Django 2.1.7 on 2019-10-29 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight_milligrams',
        ),
    ]
